### ISSUE TITLE
Picopass incorrectly emulating configuration cards

### ISSUE THREAD

**Issue by Antiklesys** [flipperdevices/flipperzero-good-faps#65] opened 2023-10-24 10:47 UTC
When trying to emulate a configuration card in personalization mode, the Flipper Zero seems to emulate it incorrectly. I have tried reading it with a Proxmark3 and the following output is shown. It seems the Flipper is somehow trying to emulate also blocks 32 to 255 while those don't exist.

<img width="466" alt="image" src="https://github.com/flipperdevices/flipperzero-good-faps/assets/8178359/7f3364e7-ff70-47f0-bfa5-4818a2f50ee4">
<img width="275" alt="image" src="https://github.com/flipperdevices/flipperzero-good-faps/assets/8178359/d1b18809-2367-409b-859e-1a09a303d37c">
<img width="293" alt="image" src="https://github.com/flipperdevices/flipperzero-good-faps/assets/8178359/beae41cc-55c4-4ac4-902c-1c43c2a3129a">
<img width="275" alt="image" src="https://github.com/flipperdevices/flipperzero-good-faps/assets/8178359/d7a2e4d7-98f5-4d9b-841b-fbc1ce225b18">
<img width="279" alt="image" src="https://github.com/flipperdevices/flipperzero-good-faps/assets/8178359/71d7058f-659b-4242-906e-01054c11b890">
<img width="280" alt="image" src="https://github.com/flipperdevices/flipperzero-good-faps/assets/8178359/0c9bc606-c35f-4ebe-aa8e-eb0c6c685329">
<img width="274" alt="image" src="https://github.com/flipperdevices/flipperzero-good-faps/assets/8178359/c45d33a8-a054-42ed-869d-0f53bb6b1884">
<img width="280" alt="image" src="https://github.com/flipperdevices/flipperzero-good-faps/assets/8178359/568dd519-068a-4d7f-93d5-ab54425a5756">

The configuration card I'm trying to emulate is attached. This works perfectly on the PM3 as well as on a card in personalization mode. 
[Config_Reset_Standard.picopass.txt](https://github.com/flipperdevices/flipperzero-good-faps/files/13113686/Config_Reset_Standard.picopass.txt)

From the flipper zero logs I couldn't seem to find anything special:

<img width="609" alt="image" src="https://github.com/flipperdevices/flipperzero-good-faps/assets/8178359/7343dc5a-5c15-46ae-8816-aa2dd473303d">

**Comment by nvx** [comment] 2023-10-24 10:52
other way around, it looks like the PM3 is trying to read blocks above 31, and the flipper isn't responding (which seems correct considering it's a 2k card).

**Comment by Antiklesys** [comment] 2023-10-24 10:55
But why would it? The picopass is emulating the dump of an actual card. If the issue was on the PM3 side it would have displayed the same behavior on the actual card to my understanding. I know picopass in the past had issues when the key was just 0s, I'm wondering here if the issue is due many of the blocks in the dump being 0s.

**Comment by nvx** [comment] 2023-10-24 10:57
Interesting, I thought you had constructed the dump by hand. There must be some difference in emulation that's triggering the PM3 to try and dump those blocks when it's not with the real card, or perhaps it always tries that but a real card responds differently vs the flipper for invalid block access.

Can you send me the PM3 trace file of doing the same command against the real card vs the flipper via Discord?

**Comment by Antiklesys** [comment] 2023-10-24 10:59
Yes I did construct the dump by hand on the Flipper but based on the dump from the card itself from the PM3, as the flipper refuses to read/dump a picopass card with "invalid data" to its saying (data is valid, just not actual credentials but instead is a config card).

Yes I'll pm you for the other bits.

**Comment by bettse** [comment] 2023-12-22 15:14
config cards aren't considered a core supported feature, so for now I'm closing this.

**Closed as not planned by bettse** 2023-12-22 15:14 UTC
Labels: bug, app:picopass

**Comment by nvx** [comment] 2023-12-24 11:02
oh yeah I forgot to reply to this, the issue is with the dump, when you run `hf iclass sim -t 3` it overrides the config block to be an iclass 2k tag using a hardcoded value - not the value in the dump file, while the flipper emulation correctly uses the dump file config block. Your config block identifies as a `[+]     Card type.... PicoPass 32K with current book 16K / 2` according to `hf iclass info` which explains with the proxmark3 is attempting to dump more than the 2k blocks.

For reference your config block is `FF FF FF FF F9 FF FF BC`, the config block the proxmark3 codebase uses is `12 FF FF FF 7F 1F FF 3C 00 00`. Changing the config block in your dump to the PM3 one will replicate the behaviour of the proxmark3 simulation code.
