### ISSUE TITLE
Memory corruption or problem with multiline strings in SPI Memory Manager

### ISSUE THREAD

**Issue by nuschpl** [flipperdevices/flipperzero-good-faps#180] opened 2024-03-10 11:27 UTC
Probably picture will be worth more than hundred words so I'm attaching:
<img width="1114" alt="obraz" src="https://github.com/flipperdevices/flipperzero-good-faps/assets/4950101/c950ebfa-71a9-4457-84e9-a93b26b7801e">
The issue I'm reporting here is not SPI itself related only the GUI part which gets broken in this specific case. 
Namely the string `Vendor id: 0x20` which should got split into two lines:
- `Vendor id:`
- `0x20`
Actually get splits into 3 lines:
- `Vendor`
- `i-`
- `d: 0x20`

So I'm betting it somehow related to multiline splitting or just memory corruption. 
The code printing it is:
``` c
 furi_string_printf(str, "Vendor\nid: 0x%02X", spi_mem_chip_get_vendor_id(app->chip_info));
    widget_add_string_multiline_element(
        app->widget, 16, 44, AlignCenter, AlignBottom, FontSecondary, furi_string_get_cstr(str));
    furi_string_printf(str, "Type\nid: 0x%02X", spi_mem_chip_get_type_id(app->chip_info));
    widget_add_string_multiline_element(
        app->widget, 64, 44, AlignCenter, AlignBottom, FontSecondary, furi_string_get_cstr(str));
    furi_string_printf(str, "Capacity\nid: 0x%02X", spi_mem_chip_get_capacity_id(app->chip_info));
    widget_add_string_multiline_element(
        app->widget, 110, 44, AlignCenter, AlignBottom, FontSecondary, furi_string_get_cstr(str));
```
I've tried to dig into the code and guessing that this is something related to:
function `elements_multiline_text_aligned` and its subsequent call to:
`size_t chars_fit = elements_get_max_chars_to_fit(canvas, horizontal, start, x);` and 
`line = furi_string_alloc_printf("%.*s-\n", chars_fit, start);` where the dash char is added. But I'm unable to quickly determine if this is bug in flipper GUI logic or in the way fapp is using those GUI calls.

**Comment by skotopes** [comment] 2024-03-11 15:52
it's not memory corruption, but incorrect text overflow handling

**Comment by nuschpl** [comment] 2024-03-12 23:12
Yes, I've realized that in the middle of writing avove with  function `widget_add_string_multiline_element` being good starting candidate.  Maybe someone familiar with how this overflow is supposed to work can point to specific logic which might be te cause here.

**Comment by portasynthinca3** [comment] 2024-09-10 12:35
I was able to reproduce the rendering issue with a static call for testing purposes, since I don't have access to your particular flash chip (or any other SPI flash chip, for that matter):
```c
widget_add_string_multiline_element(
    widget, 16, 44, AlignCenter, AlignBottom, FontSecondary, "Vendor\nid: 0x20");
```

**Update:** It seems like moving the text by two pixels to the right solves the issue. #241

**Comment by nuschpl** [comment] 2024-10-15 14:29
Just of curiosity - do we know the root cause why the moving by two pixels solves issue ? To have universal solution ?

**Comment by portasynthinca3** [comment] 2024-10-15 15:50
> Just of curiosity - do we know the root cause why the moving by two pixels solves issue ? To have universal solution ?

Yeah. Before the fix, the text drawing routine was seeing that the text overflows the screen to the left by two pixels, and was deciding to break it in the middle to avoid the overflow. By moving the text by two pixels to the right, the overflow and the consequent line break is effectively prevented. Erroneous positioning of the text is the root cause of this bug.

By the way, closing the issue because it's been solved.

**Closed as completed by portasynthinca3** 2024-10-15 15:50 UTC
Labels: bug, app:spi_mem_mgr
